language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

env:
  - DJANGO=2.0.3

branches:
  only:
    - master

services:
  - redis-server

addons:
  postgresql: "9.5"

install:
  - cd conf
  - mv settings_local.py.txt settings_local.py
  - mv .env.example .env
  - cd ..
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

script:
  - coverage run --source=muss manage.py test

after_success:
  coveralls
